-- One teacher owns this application. Provision membership separately after creating Auth user.
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS deadline text NOT NULL DEFAULT '';
ALTER TABLE public.grades ADD COLUMN IF NOT EXISTS catatan text NOT NULL DEFAULT '';
CREATE TABLE public.teacher_access (
  user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  singleton boolean NOT NULL DEFAULT true UNIQUE CHECK (singleton),
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.teacher_access ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.teacher_access FROM anon, authenticated;
GRANT SELECT ON public.teacher_access TO authenticated;
CREATE POLICY teacher_reads_own_access ON public.teacher_access FOR SELECT TO authenticated
  USING (user_id = (SELECT auth.uid()));

DO $$
DECLARE target text; old_policy record;
BEGIN
  FOREACH target IN ARRAY ARRAY['students','presensi','tasks','grades','binaan_notes','user_profile','digital_books','exclusions','tugas_exclusions'] LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', target);
    FOR old_policy IN SELECT policyname FROM pg_policies WHERE schemaname='public' AND tablename=target LOOP
      EXECUTE format('DROP POLICY %I ON public.%I', old_policy.policyname, target);
    END LOOP;
    EXECUTE format('REVOKE ALL ON public.%I FROM anon, authenticated', target);
    EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON public.%I TO authenticated', target);
    EXECUTE format('CREATE POLICY teacher_access_only ON public.%I FOR ALL TO authenticated
      USING (EXISTS (SELECT 1 FROM public.teacher_access WHERE user_id = (SELECT auth.uid())))
      WITH CHECK (EXISTS (SELECT 1 FROM public.teacher_access WHERE user_id = (SELECT auth.uid())))', target);
  END LOOP;
END $$;
-- Required for task IDs generated by the database.
DO $$
DECLARE seq text;
BEGIN
  seq := pg_get_serial_sequence('public.tasks','id');
  IF seq IS NOT NULL THEN
    EXECUTE format('REVOKE ALL ON SEQUENCE %s FROM anon', seq);
    EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO authenticated', seq);
  END IF;
END $$;
